version: '3.4'
services:
  super-app-db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: "${DATABASE}"
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
    ports:
      - '${DB_PORT}:${DB_PORT}'
    expose:
      - '${DB_PORT}'

  super-web-server:
    build: .
    ports:
      - "8000:8080"
    volumes:
      - .:/code
    environment:
      FLASK_ENV: development
  redis:
    image: "redis:alpine"